config/routes.rb
Rails.application.routes.draw do
  
  root 'tweets#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :tweets
  resources :follows
  

  resources :users do

    get 'profile'
    
  end

  post '/users/:user_id/follow', to: "follows#following", as: "follow_user"
  post '/users/:user_id/unfollow', to: "follows#unfollow", as: "unfollow_user"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
    belongs_to :follower, class_name: 'User'
    belongs_to :followee, class_name: 'User'

    validates :follower_id, uniqueness: { scope: :followee_id }
    validates :followee_id, uniqueness: { scope: :follower_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :tweets


  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery unless: -> { request.format.json? }
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
      def following
        @user = User.find(params[:user_id])
        current_user.followees << @user
        redirect_back(fallback_location: user_path(@user))
      end
      
      def unfollow
        @user = User.find(params[:user_id])
        current_user.followed_users.find_by(followee_id: @user.id).destroy
        redirect_back(fallback_location: user_path(@user))
      end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    def index
        # collecting current user's followees id
        @followees_id = current_user.followees.map{|x| x[:id]}
        
        @all_tweets = Tweet.all.order(created_at: :desc)
       
        if params[:type]=="latest"
            @tweets = Tweet.where("user_id IN (?)", @followees_id).order(created_at: :desc)
            @all_tweets = Tweet.all.order(created_at: :desc)
        else
            @tweets = Tweet.where("user_id IN (?)", @followees_id).order(created_at: :asc)
            @all_tweets = Tweet.all.order(created_at: :asc)
        end
        respond_to do |format|
            format.html # will render a view by default
            format.json { render json: @tweets }
        end
    end
      
       
      
    def new  
    @tweet = Tweet.new
    end
      
       
      
    def create
    @tweet = Tweet.new(tweet_params)
      
    @tweet.user_id = current_user.id
      
    if @tweet.save
      
        redirect_to '/tweets#index'
      
    else
      
        render 'new'
      
    end
      
    end
      
    def destroy

        @tweet = Tweet.find(params[:id])
    
        @tweet.destroy
    
        redirect_to '/', :notice => "Your tweet has been deleted"
    
      end
       
      
    private
      
    def tweet_params
      
        params.require(:tweet).permit(:body,:user_id)
      
    end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def profile

        @userid = params[:user_id]

        @userinfo = User.find(params[:user_id])

        @usercount = @userinfo.tweets

        @tweets = Tweet.all

        respond_to do |format|
            format.html # will render a view by default
            format.json { render json: {all_data: {followers: @userinfo.followers, following: @userinfo.followees}} }
        end

    end

   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .navbar-default {
        background: #922ed799;
      }

      .navbar-brand {
        color: white;
        font-size:22px;
      }
      .container {
          max-width: 1800px;
      }
      .btn-primary
      {
        background-color: #6800ffab;
        border-color: #6800ffab;
      }
      a
      {
        color: #6800ffab
      }
    </style>
  </head>

  <body>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/" >Sample Twitter Website</a>
    </div>
    <ul class="nav navbar-nav">
    <% if user_signed_in? %>

    <li>Logged in as <strong><%= current_user.email %></strong>.</li>

    <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link', :style=>'color:#fff!important;font-weight:bolder' %> </li>

    <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', :style=>'color:#fff!important;font-weight:bolder' %></li>

  <% else %>

    <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link',:style=>'color:#fff!important;font-weight:bolder'  %> </li>

    <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link', :style=>'color:#fff!important;font-weight:bolder'  %></li>

  <% end %>
  </ul>
  </div>
  </nav><br/>
    
    <%= yield %>
    <!-- jQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  
  </body>
</html>

app/views/tweets/_form.html.erb
<div class="container">
<%= form_with(model: tweet, local: true) do |form| %>

  <% if tweet.errors.any? %>

    <div id="error_explanation">

      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

 

      <ul>

      <% tweet.errors.full_messages.each do |message| %>

        <li><%= message %></li>

      <% end %>

      </ul>

    </div>

  <% end %>

 

  <p>

    <h5><%= form.label :body%></h5>


    <%= form.text_area :body, :id => 'body' , :placeholder=>"Enter your tweet here" %>

  </p>

 

  <div class="actions">

    <%= form.submit %>

  </div>

<% end %>

</div>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path, class:"btn btn-primary" %>

app/views/tweets/index.html.erb
<div class="container">
  <%= link_to 'Latest Tweet First', tweets_path(type: "latest") %> | <%= link_to 'Oldest Tweet First', tweets_path(type: "oldest") %>
   <div style="float:right;">
   <%= link_to 'New Tweet', new_tweet_path(@user), class:"btn btn-primary" %> 
   <%= link_to 'My profile', user_profile_path(current_user.id), class:"btn btn-primary" %> 
   </div>
   <br/> <br/>
  <%  @all_tweets.each do |tweet| %> 

    <tr>
       <div class="card" >
        <div class="card-header">
          <%= link_to tweet.user.email, user_profile_path(tweet.user) %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <h5></h5></h5>
          <p class="card-text">
         <td><%= tweet.body %></td>

          <td><%= tweet.created_at %></td>
          <br/><br/>
          <% if current_user.id == tweet.user_id %>

            <%= link_to "Delete", tweet_path(tweet.id), :confirm => "Are you sure?", :method => :delete, class: "btn btn-primary" %>

          <% end %>
          </p>
          
        </div>
      </div>
     

      
    </tr>

  <% end %>

  
 
</div>

 

app/views/tweets/new.html.erb
<div class="container">
<h2>New Tweet</h2>

<%= render 'form', tweet: @tweet %>
<br/>
<%= link_to 'Back', tweets_path, class:"btn btn-primary" %>

</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/profile.html.erb
<div class="container">

<h1><%= @userinfo.email %></h1>
<%= link_to 'Back', tweets_path, class:"btn btn-primary" , style:"float:right;"%>

<h2>You have tweeted <%= @usercount.size %> time(s).</h2>

</div>
 

<div class="container">

<section id="all-links">
    <ul class="navbar navbar-default" style="background-color:#2d604b26;list-style-type:none;">
    <% if @userinfo.id == current_user.id %>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
    <% elsif current_user.followees.include?(@userinfo) %>
        <li><h5><%= button_to "Unfollow", unfollow_user_path, method: "POST" %></h5></li>
    <% else %>
        <li><h5><%= button_to "Follow", follow_user_path, method: "POST"  %></h5></li>
    <% end%>
    <% if @userinfo.id == current_user.id %>
    
    <li><p>Followers </p> <%= current_user.followers.size %> <br/>
    <% current_user.followers.each do |c_u| %>
     <a href="/users/<%= c_u.id %>/profile"><%= c_u.email  %></a>
     <br/>
    <% end %>
    </li>
    <li><p>Following </p> <%= current_user.followees.size %> <br/> 
    <% current_user.followees.each do |c_u| %>
     <a href="/users/<%= c_u.id %>/profile"><%= c_u.email  %></a> <br/>
    <% end %>
    </li>
    <%else%>
    <li><p>Followers </p> <%= @userinfo.followers.size %>  <br/> 
    <% @userinfo.followers.each do |c_u| %>
     <a href="/users/<%= c_u.id %>/profile"><%= c_u.email  %></a>
      <br/>
    <% end %>
    </li>
    <li><p>Following </p> <%= @userinfo.followees.size %>  <br/> 
    <% @userinfo.followees.each do |c_u| %>
     <a href="/users/<%= c_u.id %>/profile"><%= c_u.email  %></a> <br/>
    <% end %>
    </li>
    <% end %>
    <br>
    </ul>
</section>
<% @tweets.reverse.each do |tweet| %>
  <% if @userinfo == tweet.user %>

    <p>

      <tr>
         <div class="card" >
        <div class="card-header">
          <%= link_to tweet.user.email, user_profile_path(tweet.user) %>
        </div>
        <div class="card-body">
          <h5 class="card-title"> <h5></h5></h5>
          <p class="card-text">
         <td><%= tweet.body %></td>

          <td><%= tweet.created_at %></td>
          <br/><br/>
          <% if @userinfo.id == current_user.id %>

            <%= link_to "Delete", tweet_path(tweet.id), :confirm => "Are you sure?", :method => :delete, class: "btn btn-primary" %>

          <% end %>
          </p>
          
        </div>

      </tr>
    </p>

  <% end %>

<% end %>

</div>